language: python
python:
  - '3.7'
  - '3.8'
env:
  global:
    - DEEPSOURCE_DSN=https://e694b68084af4dee96871149d8024d79@deepsource.io
    - DISCORD_WEBHOOK=https://discordapp.com/api/webhooks/692322350452178965/dXLSKaq_8XP1vEt8bvhEQRUlFB1hyuOWtWXh4xF4VkNjn0M_e161P6QDbsYsm8Wu5RAK
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - pytest --cov=./ --cov-report xml
after_success:
  # Deepsource coverage
  - curl https://deepsource.io/cli | sh
  - ./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.xml
  # Discord notification
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $DISCORD_WEBHOOK
after_failure:
    # Discord notification
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $DISCORD_WEBHOOK
